version: '3'
services:
  app:
    build: .
    container_name: tm-main
    ports:
      - "8081:8081"
    depends_on:
      - "postgres"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB: postgres

  postgres:
    container_name: tm-postgres
    restart: always
    image: postgres:9.6.8-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "teammanagement"
